/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "hyofmklgjxrletbhsode"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5b2Zta2xnanhybGV0Ymhzb2RlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE1MzQ2NjMsImV4cCI6MjA4NzExMDY2M30.Ek7Ltw5veI-UeUIpokRU73n1WTXEwRZJZM-sWmS1Sy4"